/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Analisador;
import Controller.LerFicheiro;
import Model.AreaDeTexto;
import Model.Token;
import java.awt.Color;
import java.io.File;
import java.time.Clock;
import java.util.List;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.APPROVE_OPTION;
import static javax.swing.JFileChooser.CANCEL_OPTION;
import static javax.swing.JFileChooser.OPEN_DIALOG;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Savele
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        manageEditor();
    }
    
     private void manageEditor() {
       codeEditor.setBorder(new AreaDeTexto());
    }
    
    private void openFile() {
        JFileChooser jFile = new JFileChooser(System.getProperty("user.dir"));
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.pas", "pas");
        
        jFile.addChoosableFileFilter(filter);
        jFile.setAcceptAllFileFilterUsed(false);
        
        jFile.setDialogType(OPEN_DIALOG); 
        
        int result = jFile.showOpenDialog(this);
        
        if(result == APPROVE_OPTION){
            File selectedFile = jFile.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            
            if(path.toLowerCase().endsWith("pas")) {
                LerFicheiro lf = new LerFicheiro();
                
                codeEditor.setText(lf.load(path).toString());
            }else{ 
                JOptionPane.showMessageDialog(this, "Ficheiro não suportado.\nSelecione"
                        + " ficheiro com o seguinte formato pas", "WARNING MESSAGE",JOptionPane.WARNING_MESSAGE);
            }
        }else if(result == CANCEL_OPTION){ System.out.println("CANCELED"); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
//    public void mostrarTempoExecucao(){
//        long tempo1=System.currentTimeMillis();
//        for(int i=0;i<900000000;i++){
//            
//        }
//        long tempo2
    //}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tempo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tokenClass = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        codeEditor = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        bugText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tempo de execucao:");

        tempo.setText("00");

        tokenClass.setBackground(new java.awt.Color(204, 204, 204));
        tokenClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tokenClass.setForeground(new java.awt.Color(51, 51, 51));
        tokenClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Token", "Classe", "Linha"
            }
        ));
        tokenClass.setRowMargin(5);
        jScrollPane2.setViewportView(tokenClass);

        codeEditor.setColumns(20);
        codeEditor.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        codeEditor.setLineWrap(true);
        codeEditor.setRows(5);
        codeEditor.setTabSize(4);
        jScrollPane1.setViewportView(codeEditor);

        bugText.setEditable(false);
        bugText.setColumns(20);
        bugText.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        bugText.setForeground(new java.awt.Color(204, 0, 0));
        bugText.setLineWrap(true);
        bugText.setRows(5);
        bugText.setTabSize(4);
        bugText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane3.setViewportView(bugText);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Erros");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Editor de texto");

        jButton4.setBackground(new java.awt.Color(118, 73, 91));
        jButton4.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Abrir Ficheiro");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnRun.setBackground(new java.awt.Color(0, 51, 255));
        btnRun.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        btnRun.setForeground(new java.awt.Color(255, 255, 255));
        btnRun.setText("Executar");
        btnRun.setToolTipText("Run");
        btnRun.setFocusable(false);
        btnRun.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnRun.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButton4)
                                .addGap(59, 59, 59)
                                .addComponent(btnRun)
                                .addGap(67, 67, 67)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tempo)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tempo)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       openFile();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        if (!codeEditor.getText().isEmpty()) {
            long tempo1=System.currentTimeMillis();
            catchCode();
            long tempo2=System.currentTimeMillis();
           long tempoFinal=tempo2-tempo1;
           String finalTime=Long.toString(tempoFinal);
            tempo.setText(finalTime+" miliseconds");
            seekUndefined();
           
            
        }
    }//GEN-LAST:event_btnRunActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       codeEditor.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        bugText.setText(null);
        DefaultTableModel tableModel = (DefaultTableModel) tokenClass.getModel();
        tableModel.setNumRows(0);
    }                                                                                

    
    private void catchCode() {
        DefaultTableModel tableModel = (DefaultTableModel) tokenClass.getModel();
        tableModel.setNumRows(0);
       
        Analisador analyser = new Analisador();
     
        final String[] splitedLines = codeEditor.getText().split("\n");
        int row = -1;
        int pos = 0;
        
        List<String> codeLines = analyser.scan(splitedLines);
        
        for(String line: codeLines) {
            
            for (int i = 0; i < splitedLines.length; i++) {
            
                if (splitedLines[i].contains(line) && !splitedLines[i].isEmpty()) {
                    if (line.equals(";")) { row = Integer.parseInt(String.valueOf(tableModel.getValueAt(tableModel.getRowCount()-1, 2))); }
                    
                    Token token = new Token(line, analyser.getTokenType(line), row == -1 ? i+1 : row++, pos+1);
                    
                    tableModel.addRow(new String[]{
                        token.getValue(),
                        token.getType().getTYPE(),
                        String.valueOf(token.getRow())
                    });
                    row = -1;
                    break;
                }
            }
        }
           
           
           
    }
   
        private void seekUndefined() {
        StringBuilder numLine = new StringBuilder();
        for(int i = 0; i < tokenClass.getRowCount(); i++) {
            if (!(String.valueOf(tokenClass.getValueAt(i, 1)).equalsIgnoreCase("Nao definido"))){
               numLine.append(String.valueOf(tokenClass.getValueAt(i, 2))).append(", ");
             
               
            
            } else {
                 bugText.setText("Tokens nao definidos foram encontrados. \nLinhas: "+ numLine);
            tokenClass.setBackground(Color.gray);
            }
        }
        
        
    }
        
        
    
    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Tela().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRun;
    private javax.swing.JTextArea bugText;
    private javax.swing.JTextArea codeEditor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel tempo;
    private javax.swing.JTable tokenClass;
    // End of variables declaration//GEN-END:variables
}
